# Generated by Django 5.2.6 on 2025-09-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maullidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maullido',
            options={'ordering': ['-postDate']},
        ),
    ]
