# Generated by Django 5.2.6 on 2025-09-14 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maullidos', '0002_alter_maullido_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maullido',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='maullido',
            name='likes',
        ),
        migrations.CreateModel(
            name='MaullidoReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('love', 'Love'), ('shocked', 'Shocked'), ('angry', 'Angry')], max_length=10)),
                ('maullido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='maullidos.maullido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'maullido')},
            },
        ),
    ]
