# Generated by Django 5.2.6 on 2025-09-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatarChoice',
            field=models.CharField(choices=[('blackCat', 'Gato Negro'), ('orangeCat', 'Gato Naranja'), ('whiteCat', 'Gato Blanco')], default='blackCat', max_length=20),
        ),
    ]
